import numpy as np
import math

class MLP:

    """
    Constructor: Computes MLP.

    Args:
        inputLayer (int): size of input
        hiddenLayer (int): size of hidden layer.
        outputLayer (int): size of output layer
        seed (scalar): seed of the random numeric.
        epislom (scalar) : random initialization range. e.j: 1 = [-1..1], 2 = [-2,2]...
    """

    def __init__(self,inputLayer,hidenLayer, outputLayer, seed=0, epislom = 0.12):
        np.random.seed(seed)
        ## TO-DO
        self.inputLayer = inputLayer
        self.hidenLayer = hidenLayer
        self.outputLayer = outputLayer
        self.theta1 = np.random.uniform(-epislom,epislom,size=(hidenLayer,inputLayer+1))
        self.theta2 = np.random.uniform(-epislom,epislom,size=(outputLayer,hidenLayer+1))

        """
    Reset the theta matrix created in the constructor by both theta matrix manualy loaded.

    Args:
        theta1 (array_like): Weights for the first layer in the neural network.
        theta2 (array_like): Weights for the second layer in the neural network.
    """
    def new_trained(self,theta1,theta2):
        self.theta1 = theta1
        self.theta2 = theta2
        
    """
    Num elements in the training data. (private)

    Args:
        x (array_like): input data. 
    """
    def _size(self,x):
        return x.shape[0]
    
    """
    Computes de sigmoid function of z (private)

    Args:
        z (array_like): activation signal received by the layer.
    """
    def _sigmoid(self,z):
        el = np.exp(-z)
        dev = (1/(1+el))
        return dev

    """
    Computes de sigmoid derivation of de activation (private)

    Args:
        a (array_like): activation received by the layer.
    """   
    def _sigmoidPrime(self,a):
        gp = a*(1-a)
        return gp

    """
    Run the feedwordwar neural network step

    Args:
        x (array_like): input of the neural network.

	Return 
	------
	a1,a2,a3 (array_like): activation functions of each layers
    z2,z3 (array_like): signal fuction of two last layers
    """
    def feedforward(self,x):
        a1 = x
        X1s = np.hstack([np.ones((self._size(a1), 1)), a1])
        X1s = np.transpose(X1s)
        z2 = self.theta1 @ X1s
        a2 = self._sigmoid(z2)
        X2s = np.transpose(a2)
        X2s = np.hstack([np.ones((self._size(X2s), 1)), X2s])
        X2s = np.transpose(X2s)
        z3 = self.theta2 @ X2s
        a3 = self._sigmoid(z3)
        return a1,a2,a3,z2,z3 # devolvemos a parte de las activaciones, los valores sin ejecutar la función de activación

    """
    Computes only the cost of a previously generated output (private)

    Args:
        yPrime (array_like): output generated by neural network.
        y (array_like): output from the dataset
        lambda_ (scalar): regularization parameter

	Return 
	------
	J (scalar): the cost.
    """
    def compute_cost(self, yPrime,y, lambda_): # es una función interna por eso empieza por _
        p1 = y @ np.log(yPrime)
        p2 = (1 - y) @ (np.log((1-yPrime)))

        su = p1+p2
        su = np.sum(su,axis=0).tolist()
        m = np.size(su)

        sum = np.sum(su)

        dev = (-1/m) * sum
        dev = dev + self._regularizationL2Cost(m,lambda_)
        return dev
    

    """
    Get the class with highest activation value

    Args:
        a3 (array_like): output generated by neural network.

	Return 
	------
	p (scalar): the class index with the highest activation value.
    """
    def predict(self,a3):
        p = np.argmax(a3,axis=0)
        return p
    

    """
    Compute the gradients of both theta matrix parámeters and cost J

    Args:
        x (array_like): input of the neural network.
        y (array_like): output of the neural network.
        lambda_ (scalar): regularization.

	Return 
	------
	J: cost
    grad1, grad2: the gradient matrix (same shape than theta1 and theta2)
    """
    def compute_gradients(self, x, y, lambda_):
        a1,a2,a3,z2,z3 = self.feedforward(x)
        J = self.compute_cost(a3,y,lambda_)
        dlt3 = a3.T-y
        g2 = self._sigmoidPrime(a2)
        teta2 = np.delete(self.theta2,0,axis=1)
        dlt2 = teta2 @ g2 @ dlt3
        g1 = self._sigmoidPrime(a1)
        teta1 = np.delete(self.theta1,0,axis=1)
        dlt1 = teta1 @ dlt2 @ g1.T
        ##TO-DO
        m1 = self._size(a1)
        m2 = self._size(a2)
        grad1 = (1/m1)*dlt2 @ a1.T
        grad2 = (1/m2)*dlt3.T @ a2
        grad1 = grad1 + self._regularizationL2Gradient(self.theta1,lambda_,m1)
        grad2 = grad2 + self._regularizationL2Gradient(self.theta2,lambda_,m2)
        return (J, grad1, grad2)
    
    """
    Compute L2 regularization gradient

    Args:
        theta (array_like): a theta matrix to calculate the regularization.
        lambda_ (scalar): regularization.
        m (scalar): the size of the X examples.

	Return 
	------
	L2 Gradient value
    """
    def _regularizationL2Gradient(self, theta, lambda_, m):

        teta1 = np.delete(self.theta1,0,axis=1)
        teta1 = np.sum(teta1,axis=0)
        teta1 = np.sum(teta1)
        
        teta2 = np.delete(self.theta2,0,axis=1)
        teta2 = np.sum(teta2,axis=0)
        teta2 = np.sum(teta2)

        su = teta1+teta2
        L2 = lambda_*(1/m) * su
        return L2
    
    
    """
    Compute L2 regularization cost

    Args:
        lambda_ (scalar): regularization.
        m (scalar): the size of the X examples.

	Return 
	------
	L2 cost value
    """

    def _regularizationL2Cost(self, m, lambda_):

        teta1 = np.delete(self.theta1,0,axis=1)
        teta1 = teta1 * teta1
        teta1 = np.sum(teta1,axis=0)
        teta1 = np.sum(teta1)

        teta2 = np.delete(self.theta2,0,axis=1)
        teta2 = teta2 * teta2
        teta2 = np.sum(teta2,axis=0)
        teta2 = np.sum(teta2)

        su = teta1+teta2
        L2 = lambda_*(1/(2*m)) * su
        return L2
    
    
    def backpropagation(self, x, y, alpha, lambda_, numIte, verbose=0):
        Jhistory = []
        for i in range(numIte):
            J = 0
            ##TO-DO: calculate gradients and update both theta matrix
            if verbose > 0 :
                if i % verbose == 0 or i == (numIte-1):
                    print(f"Iteration {(i+1):6}: Cost {float(J):8.4f}   ")
        
        return Jhistory
    


"""
target_gradient funcitón of gradient test 1
"""
def target_gradient(input_layer_size,hidden_layer_size,num_labels,x,y,reg_param):
    mlp = MLP(input_layer_size,hidden_layer_size,num_labels)
    J, grad1, grad2 = mlp.compute_gradients(x,y,reg_param)
    return J, grad1, grad2, mlp.theta1, mlp.theta2


"""
costNN funcitón of gradient test 1
"""
def costNN(Theta1, Theta2,x, ys, reg_param):
    mlp = MLP(x.shape[1],1, ys.shape[1])
    mlp.new_trained(Theta1,Theta2)
    J, grad1, grad2 = mlp.compute_gradients(x,ys,reg_param)
    return J, grad1, grad2


"""
mlp_backprop_predict 2 to be execute test 2
"""
def MLP_backprop_predict(X_train,y_train, X_test, alpha, lambda_, num_ite, verbose):
    mlp = MLP(X_train.shape[1],25,y_train.shape[1])
    Jhistory = mlp.backpropagation(X_train,y_train,alpha,lambda_,num_ite,verbose)
    a3= mlp.feedforward(X_test)[2]
    y_pred=mlp.predict(a3)
    return y_pred